src/objects/Rest_Log__c.object
<CustomObject>
    <description>Holds the log records for all REST API calls.</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>Holds the endpoint of the log</description>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>Holds the error code</description>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Holds the error message</description>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <description>Holds the body of the request</description>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <description>Holds the response of the rest callout</description>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Holds the status of the log</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>REST Log</label>
    <nameField>
        <displayFormat>RL-{00000}</displayFormat>
        <label>Rest Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rest Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/tests/RestLogBuilderTest.cls
/**
* @author Florian Hoehn
* tests RestLogBuilder
**/
@isTest
private class RestLogBuilderTest {
    /**
    * tests successful log which does not get inserted as the log level is set to failure.
    */
    @isTest
    private static void successLogRecordNotInserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestBody = 'expected request Body';
        String expectedResponseBody = 'expected request Body';

        Test.startTest();
            RestLogBuilder logBuilder = new RestLogBuilder();
            logBuilder.logLevel = RestLogBuilder.LOG_LEVEL_FAILURE;
            Rest_Log__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestBody(expectedRequestBody)
                                                  .withResponseBody(expectedResponseBody)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertEquals(null, actualLog.Id, 'Log is not set');
        System.assertEquals(expectedEndpoint, actualLog.Endpoint__c, 'Log Endpoint does not match');
        System.assertEquals(expectedRequestBody, actualLog.Request_Body__c, 'Log Request Body does not match');
        System.assertEquals(expectedResponseBody, actualLog.Response_Body__c, 'Log Response Body does not match');
        System.assertEquals(RestLogBuilder.STATUS_SUCCESS, actualLog.Status__c, 'Log Status does not match');
    }

    /**
    * tests successful log which does get inserted
    */
    @isTest
    private static void successLogRecordInserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestBody = 'expected request Body';
        String expectedResponseBody = 'expected request Body';

        Test.startTest();
            RestLogBuilder logBuilder = new RestLogBuilder();
            Rest_Log__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestBody(expectedRequestBody)
                                                  .withResponseBody(expectedResponseBody)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertNotEquals(null, actualLog.Id, 'Log is not set');
        System.assertEquals(expectedEndpoint, actualLog.Endpoint__c, 'Log Endpoint does not match');
        System.assertEquals(expectedRequestBody, actualLog.Request_Body__c, 'Log Request Body does not match');
        System.assertEquals(expectedResponseBody, actualLog.Response_Body__c, 'Log Response Body does not match');
        System.assertEquals(RestLogBuilder.STATUS_SUCCESS, actualLog.Status__c, 'Log Status does not match');
    }

    /**
    * tests failure log which gets inserted
    */
    @isTest
    private static void failureLogRecordInserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestBody = 'expected request Body';
        String expectedResponseBody = 'expected request Body';
        String expectedErrorCode = '400';
        String expectedexceptionText = 'expected exception message';
        JSONException expecedJsonEx = new JSONException(expectedexceptionText);

        Test.startTest();
            RestLogBuilder logBuilder = new RestLogBuilder();
            Rest_Log__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestBody(expectedRequestBody)
                                                  .withResponseBody(expectedResponseBody)
                                                  .withErrorCode(expectedErrorCode)
                                                  .withException(expecedJsonEx)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertNotEquals(null, actualLog.Id, 'Log is not set');
        System.assertEquals(expectedEndpoint, actualLog.Endpoint__c, 'Log Endpoint does not match');
        System.assertEquals(expectedRequestBody, actualLog.Request_Body__c, 'Log Request Body does not match');
        System.assertEquals(expectedResponseBody, actualLog.Response_Body__c, 'Log Response Body does not match');
        System.assertEquals(expectedResponseBody, actualLog.Response_Body__c, 'Log Response Body does not match');
        System.assertEquals(expectedErrorCode, actualLog.Error_Code__c, 'Log Error Code does not match');
        System.assertEquals(expectedexceptionText, actualLog.Message__c, 'Log Message does not match');
        System.assertEquals(RestLogBuilder.STATUS_FAILURE, actualLog.Status__c, 'Log Status does not match');
    }
}