src/objects/Rest_Log_MVN__c.object
<CustomObject>
    <description>Holds the log records for all REST API calls.</description>
    <fields>
        <fullName>Endpoint_MVN__c</fullName>
        <description>Holds the endpoint of the log</description>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code_MVN__c</fullName>
        <description>Holds the error code</description>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_MVN__c</fullName>
        <description>Holds the error message</description>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Payload_MVN__c</fullName>
        <description>Holds the payload of the request</description>
        <label>Request Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Payload_MVN__c</fullName>
        <description>Holds the response of the rest callout</description>
        <label>Response Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_MVN__c</fullName>
        <description>Holds the status of the log</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>REST Log</label>
    <nameField>
        <displayFormat>RL-{00000}</displayFormat>
        <label>Rest Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rest Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RestLogBuilderTestMVN.cls
/**
* RestLogBuilderTestMVN.cls
* Created By: Florian Hoehn
* Created On: January 16th, 2017
* Description: tests RestLogBuilderMvn
**/
@isTest
private class RestLogBuilderTestMVN {
    /**
    * @description tests successful log which does not get inserted as the log level is set to failure.
    */
    @isTest
    private static void it_should_return_SuccessLogRecord_NotInserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestPayload = 'expected request payload';
        String expectedResponsePayload = 'expected request payload';

        Test.startTest();
            RestLogBuilderMVN logBuilder = new RestLogBuilderMVN();
            logBuilder.logLevel = logBuilder.LOGLEVEL_FAILURE;
            Rest_Log_MVN__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestPayload(expectedRequestPayload)
                                                  .withResponsePayload(expectedResponsePayload)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertEquals(null, actualLog.Id); // NOT INSERTED AS LOG LEVEL IS FAILURE ONLY
        System.assertEquals(expectedEndpoint, actualLog.Endpoint_MVN__c);
        System.assertEquals(expectedRequestPayload, actualLog.Request_Payload_MVN__c);
        System.assertEquals(expectedResponsePayload, actualLog.Response_Payload_MVN__c);
        System.assertEquals(logBuilder.SUCCESS, actualLog.Status_MVN__c);
    }
    
    /**
    * @description tests successful log which does get inserted
    */
    @isTest
    private static void it_should_return_SuccessLogRecord_Inserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestPayload = 'expected request payload';
        String expectedResponsePayload = 'expected request payload';

        Test.startTest();
            RestLogBuilderMVN logBuilder = new RestLogBuilderMVN();
            Rest_Log_MVN__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestPayload(expectedRequestPayload)
                                                  .withResponsePayload(expectedResponsePayload)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertNotEquals(null, actualLog.Id);
        System.assertEquals(expectedEndpoint, actualLog.Endpoint_MVN__c);
        System.assertEquals(expectedRequestPayload, actualLog.Request_Payload_MVN__c);
        System.assertEquals(expectedResponsePayload, actualLog.Response_Payload_MVN__c);
        System.assertEquals(logBuilder.SUCCESS, actualLog.Status_MVN__c);
    }
    
    /**
    * @description tests failure log which gets inserted
    */
    @isTest
    private static void it_should_return_FailureLogRecord_Inserted() {
        String expectedEndpoint = 'expectedEndpoint';
        String expectedRequestPayload = 'expected request payload';
        String expectedResponsePayload = 'expected request payload';
        String expectedErrorCode = '400';
        String expectedExceptionText = 'expected exception message';
        JSONException expecedJsonEx = new JSONException(expectedExceptionText);

        Test.startTest();
            RestLogBuilderMVN logBuilder = new RestLogBuilderMVN();
            Rest_Log_MVN__c actualLog = logBuilder.withEndpoint(expectedEndpoint)
                                                  .withRequestPayload(expectedRequestPayload)
                                                  .withResponsePayload(expectedResponsePayload)
                                                  .withErrorCode(expectedErrorCode)
                                                  .withException(expecedJsonEx)
                                                  .insertLog()
                                                  .build();
        Test.stopTest();

        System.assertNotEquals(null, actualLog.Id);
        System.assertEquals(expectedEndpoint, actualLog.Endpoint_MVN__c);
        System.assertEquals(expectedRequestPayload, actualLog.Request_Payload_MVN__c);
        System.assertEquals(expectedResponsePayload, actualLog.Response_Payload_MVN__c);
        System.assertEquals(expectedResponsePayload, actualLog.Response_Payload_MVN__c);
        System.assertEquals(expectedErrorCode, actualLog.Error_Code_MVN__c);
        System.assertEquals(expectedExceptionText, actualLog.Message_MVN__c);
        System.assertEquals(logBuilder.FAILURE, actualLog.Status_MVN__c);
    }
}